---
# NetworkPolicy to allow access from any namespace to access
# the RHOAI Prometheus instance in redhat-ods-monitoring
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-prometheus-access
  namespace: redhat-ods-monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: data-science-monitoringstack
      app.kubernetes.io/name: prometheus
  policyTypes:
    - Ingress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 9090
