---
# PostgreSQL Deployment for Keycloak
kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak-pgsql
  namespace: keycloak
  labels:
    app: keycloak-pgsql
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-pgsql
  template:
    metadata:
      labels:
        app: keycloak-pgsql
    spec:
      volumes:
        - name: pgsql-storage
          persistentVolumeClaim:
            claimName: keycloak-pgsql-data
      containers:
        - name: pgsql
          image: 'registry.redhat.io/rhel9/postgresql-16:1-1754433677'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql-user
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql-user
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql-user
                  key: dbname
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: pgsql-storage
              mountPath: /var/lib/pgsql/data
      restartPolicy: Always
