---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdu-website
  namespace: ai501
  labels:
    app: rdu-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdu-website
  template:
    metadata:
      labels:
        app: rdu-website
    spec:
      containers:
      - name: rdu-website
        image: quay.io/rhoai-genaiops/rdu-website:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 25m
            memory: 32Mi